///<summary>
/// GENERATED BY VIEW INCLUDE
/// 
///** Name:  XXROTO.CS
///** View:  Roto IDs
///** Copyright (c) 1992-2016 Sage Software, Inc.  All rights reserved.
///</summary>
public class XXROTO
{
    public const string ROTOID        = "XX0100  ";

    #region View Field Indices
    public const int IDX_PGMID      = 1;
    public const int IDX_ROTOTYPE   = 2;
    public const int IDX_OBJECTID   = 3;
    public const int IDX_OBJECTNAME = 4;
    public const int IDX_OPERATION  = 5;
    public const int IDX_WRITESTR   = 6;
    public const int IDX_FILENAME   = 7;
    public const int IDX_GENERATE   = 8;

    #endregion

    public const int OPERATION_GetRotoList = 0;
    public const int ROTOTYPE_View = 2;

    //#region Public Members
    //public AccpacView View
    //{
    //    get
    //    {
    //        return this._View;
    //    }
    //}
    //#endregion

    //#region Private Members
    //private AccpacView _View = null;
    //#endregion

    //#region Constructor
    //public XXROTO()
    //{
    //}

    //public XXROTO(AccpacDBLink _dbLink)
    //{
    //    this.Open(_dbLink);
    //}
    //#endregion

    //#region Destructor
    //~XXROTO()
    //{
    //    this.Close();
    //}
    //#endregion

    //public void Open(AccpacDBLink _dbLink)
    //{
    //    if (this._View != null)
    //        return;

    //    _dbLink.OpenView(XXROTO.ROTOID, out this._View);
    //}

    //public void Close()
    //{
    //    if (this._View == null)
    //        return;

    //    this._View.Close();
    //    this._View = null;
    //}

    //public void Get()
    //{
    //}

    //public void Put(Int32 lIDX, string sValue, bool bValidate)
    //{
    //    Object oValue = new Object();
    //    oValue = sValue;

    //    if (bValidate)
    //        this._View.Fields.get_FieldByID(lIDX).set_Value(ref oValue);
    //    else
    //        this._View.Fields.get_FieldByID(lIDX).PutWithoutVerification(ref oValue);
    //}
}
